# Generated by Django 5.0.7 on 2024-07-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('phone_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredToSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_saved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identities.identity')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identities.registered')),
            ],
        ),
    ]
