# Generated by Django 5.0.7 on 2024-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_spam',
            field=models.IntegerField(default=0),
        ),
    ]
