# Generated by Django 5.0.7 on 2024-07-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0002_identity_is_spam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='identity',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='identity',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='identity',
            name='last_name',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
    ]
