# Generated by Django 5.0.7 on 2024-07-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0003_rename_email_address_identity_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='registered',
            name='last_name',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
    ]
