# Generated by Django 5.0.7 on 2024-07-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0004_rename_name_registered_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
