# Generated by Django 5.0.7 on 2024-07-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0005_rename_email_address_registered_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredtosaved',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
