# Generated by Django 5.0.7 on 2024-07-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0006_rename_phone_number_registeredtosaved_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('first_name', 'last_name', 'phone', 'email')},
        ),
    ]
