# Generated by Django 5.0.7 on 2024-07-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0007_alter_identity_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('first_name', 'last_name', 'phone', 'email', 'is_spam')},
        ),
    ]
